<?php

namespace JeffersonGoncalves\Commerce;

use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class CommerceServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        $package->name('laravel-commerce')
            ->hasConfigFile('commerce')
            ->hasTranslations()
            ->hasRoutes([
                'admin',
                'store',
            ])
            ->hasMigrations([
                'create_commerce_api_keys_table',
                'create_commerce_auth_identities_table',
                'create_commerce_provider_identities_table',
                'create_commerce_carts_table',
                'create_commerce_cart_line_items_table',
                'create_commerce_cart_shipping_methods_table',
                'create_commerce_currencies_table',
                'create_commerce_customers_table',
                'create_commerce_customer_groups_table',
                'create_commerce_customer_addresses_table',
                'create_commerce_customer_group_customer_table',
                'create_commerce_fulfillment_sets_table',
                'create_commerce_service_zones_table',
                'create_commerce_shipping_options_table',
                'create_commerce_fulfillments_table',
                'create_commerce_fulfillment_items_table',
                'create_commerce_inventory_items_table',
                'create_commerce_inventory_levels_table',
                'create_commerce_reservation_items_table',
                'create_commerce_loyalty_accounts_table',
                'create_commerce_loyalty_transactions_table',
                'create_commerce_orders_table',
                'create_commerce_order_line_items_table',
                'add_cart_id_to_commerce_orders_table',
                'create_commerce_order_transactions_table',
                'create_commerce_returns_table',
                'create_commerce_return_items_table',
                'create_commerce_exchanges_table',
                'create_commerce_exchange_items_table',
                'create_commerce_claims_table',
                'create_commerce_claim_items_table',
                'create_commerce_payment_collections_table',
                'create_commerce_payment_sessions_table',
                'create_commerce_payments_table',
                'create_commerce_captures_table',
                'create_commerce_refunds_table',
                'create_commerce_price_sets_table',
                'create_commerce_price_lists_table',
                'create_commerce_prices_table',
                'create_commerce_price_rules_table',
                'create_commerce_product_collections_table',
                'create_commerce_product_types_table',
                'create_commerce_product_tags_table',
                'create_commerce_product_categories_table',
                'create_commerce_products_table',
                'create_commerce_product_options_table',
                'create_commerce_product_option_values_table',
                'create_commerce_product_variants_table',
                'create_commerce_product_images_table',
                'create_commerce_product_category_product_table',
                'create_commerce_product_product_tag_table',
                'create_commerce_product_variant_option_value_table',
                'add_price_set_id_to_commerce_product_variants_table',
                'create_commerce_campaigns_table',
                'create_commerce_promotions_table',
                'create_commerce_promotion_rules_table',
                'create_commerce_application_methods_table',
                'create_commerce_regions_table',
                'create_commerce_countries_table',
                'create_commerce_sales_channels_table',
                'create_commerce_stock_locations_table',
                'create_commerce_stores_table',
                'create_commerce_store_credit_accounts_table',
                'create_commerce_store_credit_transactions_table',
                'create_commerce_tax_regions_table',
                'create_commerce_tax_rates_table',
                'create_commerce_translations_table',
                'create_commerce_users_table',
            ]);
    }
}
