name: Split Monorepo

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - { local: suite,    split: laravel-commerce-suite }
          - { local: core,     split: laravel-commerce-core }
          - { local: currency,      split: laravel-commerce-currency }
          - { local: store,         split: laravel-commerce-store }
          - { local: sales-channel, split: laravel-commerce-sales-channel }
          - { local: region,         split: laravel-commerce-region }
          - { local: stock-location, split: laravel-commerce-stock-location }
          - { local: api-key,        split: laravel-commerce-api-key }
          - { local: user,           split: laravel-commerce-user }
          - { local: auth,           split: laravel-commerce-auth }
          - { local: product,        split: laravel-commerce-product }
          - { local: pricing,        split: laravel-commerce-pricing }
          - { local: inventory,      split: laravel-commerce-inventory }
          - { local: customer,       split: laravel-commerce-customer }
          - { local: tax,            split: laravel-commerce-tax }
          - { local: cart,           split: laravel-commerce-cart }

    name: Split ${{ matrix.package.split }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Split (branch)
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: symplify/monorepo-split-github-action@v2.3.0
        with:
          package_directory: 'packages/${{ matrix.package.local }}'
          repository_organization: jeffersongoncalves
          repository_name: ${{ matrix.package.split }}
          branch: ${{ github.ref_name }}
          user_name: jeffersongoncalves
          user_email: gerson.simao.92@gmail.com
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_TOKEN }}

      - name: Split (tag)
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: symplify/monorepo-split-github-action@v2.3.0
        with:
          tag: ${{ github.ref_name }}
          package_directory: 'packages/${{ matrix.package.local }}'
          repository_organization: jeffersongoncalves
          repository_name: ${{ matrix.package.split }}
          user_name: jeffersongoncalves
          user_email: gerson.simao.92@gmail.com
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_TOKEN }}
